services:
  slurmjupyter:
        build:
            context: jupyter
            dockerfile: Dockerfile
        image: slurm-jupyter:19.05.5-1
        container_name: headnode
        hostname: slurmjupyter
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 8888:8888
  slurmmaster:
        build:
            context: master
            dockerfile: Dockerfile
        image: slurm-master:19.05.5-1
        container_name: master
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        build:
            context: node
            dockerfile: Dockerfile
        image: slurm-node:19.05.5-1
        container_name: node1
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin
        links:
                - slurmmaster
  slurmnode2:
        image: slurm-node:19.05.5-1
        container_name: node2
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin
        links:
                - slurmmaster
  slurmnode3:
        image: slurm-node:19.05.5-1
        container_name: node3
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin
        links:
                - slurmmaster
volumes:
        shared-vol:

